COMPANY_PORTALS = {
    "tcs": {
        "name": "TCS iBegin",
        "signup_url": "https://ibegin.tcs.com/iBegin/",
        "login_url": "https://ibegin.tcs.com/iBegin/",
        "username_selector": "input[name='email'], input[id='email'], input[type='email']",
        "password_selector": "input[type='password']",
        "submit_selector": "button[type='submit'], input[type='submit']",
        "success_indicator": ".dashboard, #dashboard, .home-page, .profile-section",
        "chrome_profile_subdir": "tcs",
    },
    "infosys": {
        "name": "Infosys Careers",
        "signup_url": "https://career.infosys.com/register",
        "login_url": "https://career.infosys.com/login",
        "username_selector": "input[name='email'], input[id='email']",
        "password_selector": "input[name='password'], input[type='password']",
        "submit_selector": "button[type='submit']",
        "success_indicator": ".candidate-dashboard, .profile-section, .my-applications",
        "chrome_profile_subdir": "infosys",
    },
    "cognizant": {
        "name": "Cognizant Careers",
        "signup_url": "https://careers.cognizant.com/global/en/register",
        "login_url": "https://careers.cognizant.com/global/en/login",
        "username_selector": "input[type='email'], input[name='email']",
        "password_selector": "input[type='password']",
        "submit_selector": "button[type='submit']",
        "success_indicator": ".logged-in, .account-nav, .user-profile",
        "chrome_profile_subdir": "cognizant",
    },
    "wipro": {
        "name": "Wipro Careers",
        "signup_url": "https://careers.wipro.com/careers-home/",
        "login_url": "https://careers.wipro.com/careers-home/",
        "username_selector": "input[type='email']",
        "password_selector": "input[type='password']",
        "submit_selector": "button[type='submit']",
        "success_indicator": ".loggedin-nav, .user-account, .nav-signed-in",
        "chrome_profile_subdir": "wipro",
    },
    "hcl": {
        "name": "HCL Technologies",
        "signup_url": "https://www.hcltech.com/careers",
        "login_url": "https://hcl.taleo.net/careersection/hcl_professional/jobsearch.ftl",
        "username_selector": "input[name='j_username']",
        "password_selector": "input[name='j_password']",
        "submit_selector": "input[type='submit'], button[type='submit']",
        "success_indicator": ".candidate-dashboard, .loggedIn",
        "chrome_profile_subdir": "hcl",
    },
}
